version: '3'
x-environment:
    &airflow_environment
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres:5432/airflow
    - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
    - AIRFLOW__WEBSERVER__RBAC=False
    - AIRFLOW__WEBSERVER__COOKIE_SAMESITE=None

x-spark-image: &spark-image chunguyenduc/job_etl_pipeline_spark:0.0.1
x-airflow-image: &airflow-image chunguyenduc/job_etl_pipeline_airflow:0.0.3
x-superset-image: &superset-image apache/superset:latest
x-superset-user: &superset-user root
x-superset-depends-on:
    &superset-depends-on
    - postgres
    - redis
x-superset-volumes:
    &superset-volumes
    - ./superset/docker:/app/docker
    - superset_home:/app/superset_home

services:
    redis:
        image: redis:latest
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - "5432:5432"
    initdb_adduser:
        image: *airflow-image
        depends_on:
            - postgres
        environment: *airflow_environment
        container_name: airflow_init
        entrypoint: /bin/bash
        command: -c 'airflow db upgrade && airflow db init && airflow users create --username admin --password admin --firstname Anonymous --lastname Admin --role Admin --email admin@example.org && airflow sync-perm'

    webserver:
        image: *airflow-image
        container_name: airflow_webserver
        depends_on:
            - postgres
        volumes:
            - ./airflow/logs:/opt/airflow/logs
            - ./airflow/dags:/opt/airflow/dags
        ports:
            - "8080:8080"
        # restart: on-failure
        environment: *airflow_environment
        command: webserver

    scheduler:
        image: *airflow-image
        container_name: airflow_scheduler
        depends_on:
            - postgres
        # restart: on-failure
        volumes:
            - ./airflow/dags:/opt/airflow/dags
            - ./airflow/logs:/opt/airflow/logs
        environment: *airflow_environment
        command: scheduler

    spark:
        image: *spark-image
        user: root
        container_name: spark
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
            - SPARK_EXECUTOR_MEMORY=4G

        volumes:
            - ./airflow/dags/transform:/opt/airflow/dags/transform
        ports:
            - "8181:8080"
            - "7077:7077"
    spark-worker:
        image: *spark-image
        user: root
        depends_on:
            - spark
        container_name: spark_worker
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=8G
            - SPARK_EXECUTOR_MEMORY=4G
            - SPARK_WORKER_CORES=4
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - ./airflow/dags/transform:/opt/airflow/dags/transform

    superset:
        image: *superset-image
        container_name: superset
        command: [ "/app/docker/docker-bootstrap.sh", "app" ]
        restart: unless-stopped
        ports:
            - 8088:8088
        user: *superset-user
        depends_on: *superset-depends-on
        volumes: *superset-volumes

    superset-init:
        image: *superset-image
        container_name: superset_init
        command: [ "/app/docker/docker-init.sh" ]
        depends_on: *superset-depends-on
        user: "root"
        volumes: *superset-volumes
        environment:
            SUPERSET_LOAD_EXAMPLES: "no"
    prometheus:
        image: prom/prometheus:latest
        container_name: monitoring_prometheus
        restart: unless-stopped
        volumes:
            - ./data/prometheus/config:/etc/prometheus/
            - ./data/prometheus/data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        expose:
            - 9090
        ports:
            - 9090:9090
        links:
            - cadvisor:cadvisor
            - node-exporter:node-exporter

    node-exporter:
        image: prom/node-exporter:latest
        container_name: monitoring_node_exporter
        restart: unless-stopped
        expose:
            - 9100

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        container_name: monitoring_cadvisor
        restart: unless-stopped
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /var/run/docker.sock:/var/run/docker.sock:rw
        ports:
            - 8083:8080

    grafana:
        image: grafana/grafana:latest
        container_name: monitoring_grafana
        restart: unless-stopped
        links:
            - prometheus:prometheus
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP=false
        ports:
            - 3000:3000

    metabase:
        image: metabase/metabase:latest
        container_name: metabase
        restart: unless-stopped
        ports:
            - 3000:3000

volumes:
    superset_home:
        external: false
