version: '2'
services:
  db:
    image: mongo
  api:
    build:
      context: ./skills_dashboard/
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./skills_dashboard:/code
    ports:
      - "8000:8000"
    # depends_on:
      # - db
    tty: true
  crawl:
    build:
      context: ./skills_dashboard/
    command: bash -c "cd skillscraper && scrapyd"
    volumes:
      - ./skills_dashboard:/code
    ports:
      - "6800:6800"
    tty: true
    stdin_open: true