version: '3'
x-environment:
    &airflow_environment
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres:5432/airflow
    - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
    - AIRFLOW__WEBSERVER__RBAC=False
    - AIRFLOW__WEBSERVER__COOKIE_SAMESITE=None

x-spark-image: &spark-image chunguyenduc/job_etl_pipeline_spark:0.0.1
x-airflow-image: &airflow-image chunguyenduc/job_etl_pipeline_airflow:0.0.4
x-superset-image: &superset-image apache/superset:latest
x-superset-user: &superset-user root
x-superset-depends-on:
    &superset-depends-on
    - postgres
    - redis
x-superset-volumes:
    &superset-volumes
    - ./superset/docker:/app/docker
    - superset_home:/app/superset_home

services:
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - "5432:5432"
    airflow_init:
        image: *airflow-image
        depends_on:
            - postgres
        environment: *airflow_environment
        container_name: airflow_init
        entrypoint: /bin/bash
        command: -c 'airflow db upgrade && airflow db init && airflow users create --username admin --password admin --firstname Anonymous --lastname Admin --role Admin --email admin@example.org && airflow sync-perm'

    airflow_webserver:
        image: *airflow-image
        container_name: airflow_webserver
        depends_on:
            - postgres
        volumes:
            - ./airflow/logs:/opt/airflow/logs
            - ./airflow/dags:/opt/airflow/dags
        ports:
            - "8080:8080"
        # restart: on-failure
        environment: *airflow_environment
        command: webserver

    ariflow_scheduler:
        image: *airflow-image
        container_name: airflow_scheduler
        depends_on:
            - postgres
        # restart: on-failure
        volumes:
            - ./airflow/dags:/opt/airflow/dags
            - ./airflow/logs:/opt/airflow/logs
        environment: *airflow_environment
        command: scheduler

    metabase:
        image: metabase/metabase:latest
        container_name: metabase
        restart: unless-stopped
        ports:
            - 3000:3000

volumes:
    superset_home:
        external: false
