name: Validate DAGs
on:
  workflow_dispatch:
  push:
    branches:
      - dev 
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      

      - name: Build image 
        uses: docker/build-push-action@v3
        with:
          context: airflow
          tags: test-image:latest
          push: false

      - name: Unit test 
        uses: addnab/docker-run-action@v3
        with:
          options: -v ${{ github.workspace }}/airflow/dags:/opt/airflow/dags
          image: test-image:latest
          run: "airflow db init && \
                ./unittest.sh"