name: Validate DAGs
on:
  workflow_dispatch:
  push:
    branches:
      - dev 
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image 
        uses: docker/build-push-action@v2
        with:
          context: airflow
          tags: test-image:latest
          push: false
  test:
    needs: job1
    runs-on: ubuntu-latest
    container:
      image: test-image:latest
      volumes:
        - ./airflow/logs:/opt/airflow/logs
        - ./airflow/dags:/opt/airflow/dags
    steps:
      - name: Unit test
        run: "./unittest.sh"