name: Validate DAGs
on:
  workflow_dispatch:
  push:
    branches:
      - dev 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image 
        uses: docker/build-push-action@v2
          with:
            context: airflow
            tags: test-image:latest
            push: false
      - name: Unit test
        uses: addnab/docker-run-action@v3
          with:
            image: test-image:latest
            run: "./unittest.sh"