name: CI/CD 
on:
  workflow_dispatch:
  push:
    branches:
      - dev 
env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
  TAG_VERSION: $(git rev-parse --short "$GITHUB_SHA") 

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image 
        uses: docker/build-push-action@v3
        with:
          context: airflow
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG_VERSION }}
          push: true

      - name: Unit test 
        uses: addnab/docker-run-action@v3
        with:
          options: -v ${{ github.workspace }}/airflow/dags:/opt/airflow/dags
          image: ${{ env.IMAGE_NAME }}:${{ env.TAG_VERSION }}
          run: "airflow db init && \
                ./unittest.sh"

      - name: Deploy EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script:  | 
            set -x
            cd ${{ github.event.repository.name }}
            git checkout ${GITHUB_REF##*/}
            git pull origin ${GITHUB_REF##*/} 
            docker-compose stop
            AIRFLOW_BUILD_IMAGE=$${{ env.IMAGE_NAME }} TAG=$${{ env.TAG_VERSION }} docker-compose up -d

      


    