name: Validate DAGs
on:
  workflow_dispatch:
  push:
    branches:
      - dev 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Validate DAGs'
        uses: jayamanikharyono/airflow-dag-action@v2.3
        with:
          requirementsFile: airflow/requirements.txt
          dagPaths: airflow/dags
          varFile: airflow/dags/tests/var.json
          connFile: airflow/dags/tests/conns.json
          loadExample: False
          accessToken: ${{ secrets.GITHUB_TOKEN }}